import { Nunito } from "next/font/google";
import ToasterProvider from "./ToasterProvider/ToasterProvider";
import Provider from "./components/Provider";
import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Provider>
          <ToasterProvider />
          <Navbar />
          <SearchModal />
          <LoginModal />
          <RegisterModal />
          <RentModal />
          <div className="pb-20 pt-28">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
